# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.

# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: RH Designs
email: rosemarie.m.halim@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
   Rose is a young freelancer with a goal to create new solutions using communication and innovation.

baseurl: "/home" # the subpath of your site, e.g. /blog
url: "https://rosemariehalim.ca" # the base hostname & protocol for your site, e.g. http://example.com

markdown: kramdown

permalink: /:categories/:title/

sass:
  style: compact # possible values: nested expanded compact compressed